export const SECONDS_LEFT_TO_NEXT_EPISODE = 5;
export const SECONDS_LEFT_TO_TRIGGER_NEXT_EPISODE = 1;
export const SECONDS_NEXT_BUTTON_DISPLAY = SECONDS_LEFT_TO_NEXT_EPISODE - SECONDS_LEFT_TO_TRIGGER_NEXT_EPISODE;