export const SECONDS_LEFT_TO_NEXT_EPISODE = 100
export const SECONDS_NEXT_BUTTON_DISPLAY = 4
export const SECONDS_LEFT_TO_TRIGGER_NEXT_EPISODE =
    SECONDS_LEFT_TO_NEXT_EPISODE - SECONDS_NEXT_BUTTON_DISPLAY
export const RATIO_TO_FOLLOW_AN_ANIME = 0.7
